### ISSUE TITLE
tapCircle variable sometimes  is nil

### ISSUE THREAD

**Issue by Maguszin** [bfeher/BFPaperTabBarController#10]
In my app sometimes this variable returns nil when the user fast switch between views, i could not reproduce the problem in the demo app, and since my views do some heavy work when loading a think it may have something to do with that process.
I made a simple change in the burstTapCircle method, just add a nil check and it seem to solve the my problem and didn't change any behavior in the component

    if (tapCircle != nil) {
        [self.deathRowForCircleLayers addObject:tapCircle];
        
        
        CGPathRef startingPath = tapCircle.path;
        CGFloat startingOpacity = tapCircle.opacity;
        
        if ([[tapCircle animationKeys] count] > 0) {
            startingPath = [[tapCircle presentationLayer] path];
            startingOpacity = [[tapCircle presentationLayer] opacity];
        }
        
        // Burst tap-circle:
        CABasicAnimation *tapCircleGrowthAnimation = [CABasicAnimation animationWithKeyPath:@"path"];
        tapCircleGrowthAnimation.duration = self.touchUpAnimationDuration;
        tapCircleGrowthAnimation.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseOut];
        tapCircleGrowthAnimation.fromValue = (__bridge id)startingPath;
        tapCircleGrowthAnimation.toValue = (__bridge id)endingCirclePath.CGPath;
        tapCircleGrowthAnimation.fillMode = kCAFillModeForwards;
        tapCircleGrowthAnimation.removedOnCompletion = NO;
        
        // Fade tap-circle out:
        CABasicAnimation *fadeOut = [CABasicAnimation animationWithKeyPath:@"opacity"];
        [fadeOut setValue:@"fadeCircleOut" forKey:@"id"];
        fadeOut.delegate = self;
        fadeOut.fromValue = [NSNumber numberWithFloat:startingOpacity];
        fadeOut.toValue = [NSNumber numberWithFloat:0.f];
        fadeOut.duration = self.touchUpAnimationDuration;
        fadeOut.fillMode = kCAFillModeForwards;
        fadeOut.removedOnCompletion = NO;
        
        [tapCircle addAnimation:tapCircleGrowthAnimation forKey:@"animatePath"];
        [tapCircle addAnimation:fadeOut forKey:@"opacityAnimation"];
        
    }

**Comment by bfeher** [comment]
Hi Maguszin!

Thanks for pointing this out. I pushed a new version, 2.1.9 which included this fix!
