### ISSUE TITLE
BFPaperTabBarController hide bug

### ISSUE THREAD

**Issue by smiledark** [bfeher/BFPaperTabBarController#11]
Use the hidesBottomBarWhenPushed came up the controller, the TabBar disappeared , but the click of a button and the event will continue
Not to use the BFPaperTabBarController
tabbar area normally disappear
How do I fix this bug ?

**Comment by bfeher** [comment]
Could you show me some code or a gif/gifv of this happening?
If I'm understanding you correctly, the demo project does not behave that way and does not replicate that bug while doing the same exact thing.

**Comment by smiledark** [comment]
https://youtu.be/CygaTsOmy1Y

**Comment by bfeher** [comment]
Thanks for the video! Which version of iOS are you running? I can't seem to duplicate this bug yet.

**Comment by bfeher** [comment]
I have just tried it again with iOS SDK 8.4 on the iOS 8.4 simulators with no problem using both storyboard push/show, and programmatic push/show. I really cannot replicate this bug :(

**Comment by smiledark** [comment]
I used SDK & iOS 8.4 so only programmatic push/show. no storyboard push/show

I used storyboard no problem
