### ISSUE TITLE
Setting selectedIndex programmatically does not set the tab underline

### ISSUE THREAD

**Issue by bhagyas** [bfeher/BFPaperTabBarController#12]

**Comment by bfeher** [comment]
Hi @bhagyas 

As is written in the documentation, please use this function when programmatically selecting tabs. My apologies if it wasn't clear.
```objective-c
(void)selectTabAtIndex:(NSInteger)index animated:(BOOL)animated
```
Selects and highlights a tab.
@param index (NSInteger) The index of the tab you wish to select and highlight.
@param animated (BOOL) A flag to determine if we should animate the change or not.

**Comment by bhagyas** [comment]
Hi @bfeher,

Thank you for your response. That solved the issue. 

I'm wondering if there is a way to have the selectedIndex setter to automatically call selectTabAtIndex method. This could help more people to move over from the default TabBarController to the more awesome BFPaperTabBarController. :-)
