### ISSUE TITLE
How to change inactive item color

### ISSUE THREAD

**Issue by sagits** [bfeher/BFPaperTabBarController#14]
Hi, how can i change the inactive icon text and image color/tint? I mean, i want the unselected items to be red, and the selected one to be white, but i wasnt able to change the inactive items color. Can you help me? Thanks in advance.

**Comment by bfeher** [comment]
Hi sagits!

Yes if I understand you correctly, it should be as easy as adding this to your AppDelegate:

```
[[UITabBarItem appearance] setTitleTextAttributes:@{ NSForegroundColorAttributeName : [UIColor redColor] }
                                         forState:UIControlStateNormal];
[[UITabBarItem appearance] setTitleTextAttributes:@{ NSForegroundColorAttributeName : [UIColor whiteColor] }
                                         forState:UIControlStateSelected];
```

If you are using images you may need to set them to 'OriginalImage' like this:
```
UIImage *deselectedImage = [[UIImage imageNamed:@"deselectedImage"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
UIImage *selectedImage = [[UIImage imageNamed:@"selectedImage"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
```

This is all standard UIKit code and should not have any problems with BFPaperTabBarController.
