### ISSUE TITLE
Double tap on tab does not pop to root navigation controller

### ISSUE THREAD

**Issue by tobiaghiraldini** [bfeher/BFPaperTabBarController#15]
When using the default tabbar controller each tab can provide a way to pop to its inner root controller within each navigation stack, by tapping twice on each tab. Here i cannot get the same behaviour: the second tap on a tab just does nothing.

**Comment by bfeher** [comment]
Hi @tobiaghiraldini 

Sorry for the late response. I will look into recreating this feature in a future release. Unfortunately I will be on vacation from next week until mid January so I most likely won't be able to get it done until after then.

In the meantime, if you feel up to it, you can always submit a pull request if you happen to implement this feature on your own ;)

**Comment by bfeher** [comment]
It has been 1.5 years since I forgot about this but the feature finally is here in version 2.2.9.
Thanks!
