### ISSUE TITLE
compile error for 9.3 beta

### ISSUE THREAD

**Issue by tobatha** [bfeher/BFPaperTabBarController#18]
￼
![image](https://cloud.githubusercontent.com/assets/2382153/13203069/45772cea-d8e9-11e5-8d7e-17b94c377d5c.png)

seems there's this weird error, and suggested correction didn't work. Anybody run into this issue yet?

lemme know, thank you very much!

**Comment by tobatha** [comment]
oh, by the way, same thing happened with BFPaperButton

**Comment by bfeher** [comment]
Hi @tobatha !

Thanks for using these controls and submitting this issue :)

That is a super weird error as `startingPath` is a `CGPathRef` and `[[tapCircle presentationLayer] path]` returns a `CGPathRef`.

I'm willing to bet that either the 9.3 beta is unstable (as every iOS sdk beta has ever been) or that something `[[tapCircle presentationLayer] path]` has changed drastically. I'm leaning more towards the first one.

I'm using iOS SDK 9.2 and everything is working as expected. I don't know what else to tell you other than to not use beta versions for code/projects you need to publish as they are always riddled with bugs and broken content.

However, if you can reproduce this in iOS 9.2, or at least expand that error message so we can read its contents fully, that would definitely help in pinpointing the issue.

Thank you :)
