### ISSUE TITLE
Not move item on current tabbar

### ISSUE THREAD

**Issue by nghienpgcpt** [bfeher/BFPaperTabBarController#20]
BFPaperTabBar allow change position on current tabbar, but BFPaperTabBarController not allow. Please you support this!

**Comment by bfeher** [comment]
Hi @nghienpgcpt!

I'm sorry but I don't understand your issue. BFPaperTabBarController does allow reordering tabs, as you can see in the gif in the README file.

However, I have a feeling that this isn't your issue and its something else. Is there any way you can show me?

Thanks.

**Comment by nghienpgcpt** [comment]
Thank you @bfeher 

It mean reordering tabs on current tabbar display (tab 1, tab 2, tab 3, tab 4), I can't change positions between them, i must be replace by other tab

**Comment by bfeher** [comment]
Okay I understand. Where you using `[tabBar beginCustomizingItems:items]`?

Unfortunately, once we use a UITabBarController, we can no longer directly manipulate the UITabBar and will get this error:
```
'NSInternalInconsistencyException', reason: 
'Directly modifying a tab bar managed by a tab bar controller is not allowed.'
```

Apple documentation on UITabBarController also states this is not possible :(
I haven't figured out a way around this yet.

I'm sorry but this feature doesn't seem possible for now :(

**Comment by nghienpgcpt** [comment]
Thanks @bfeher
