### ISSUE TITLE
Compatibilities with swift

### ISSUE THREAD

**Issue by xuanzi23** [bfeher/BFPaperTabBarController#25]
I working a project with swift language.
After I pod install and try to do with it, i found out some how my tab bar same as before does not have the underline below tab bar.

Why?

![screen shot 2016-12-28 at 10 33 18 am](https://cloud.githubusercontent.com/assets/19340910/21512505/3945abaa-cce9-11e6-8c90-801b9625eaac.png)

**Comment by bfeher** [comment]
Hi @xuanzi23!

Unfortunately BFPaperTabBarController only supports Interface Builder. To get it working programmatically, try this:
https://github.com/Timstarockz/BFPaperTabBarController/tree/master/Classes

Thanks.

**Comment by xuanzi23** [comment]
In interface builder how I setting for the underline?

**Comment by bfeher** [comment]
I'm not sure why your code above isn't working actually. I will have to try to use this library in Swift to find out.

In the meantime, to answer your question, it is IBInspectable so you can set it in the Attributes Inspector panel:

![bftabbarcontroller-attributes-inspector](https://cloud.githubusercontent.com/assets/3466708/21515848/81613454-cd16-11e6-8af4-e4bb2366f926.png)

**Comment by xuanzi23** [comment]
@bfeher (void)selectTabAtIndex:(NSInteger)index animated:(BOOL)animated this function how to use it?

**Comment by bfeher** [comment]
```objective-c
#pragma mark - Utility Functions
/**
 *  Selects and highlights a tab.
 *
 *  @param index    (NSInteger) The index of the tab you wish to select and highlight.
 *  @param animated (BOOL) A flag to determine if we should animate the change or not.
 */
- (void)selectTabAtIndex:(NSInteger)index animated:(BOOL)animated;
```

Inside of your BFPaperTabBarController subclass:
```objective-c
[self selectTabAtIndex:2 animated:NO];
```

Outside of your BFPaperTabBarController subclass:
```objective-c
[bfPaperTBC selectTabAtIndex:2 animated:NO];
```

**Comment by bfeher** [comment]
If you haven't already, please take a look at the demo project.

```
$ pod try BFPaperTabBarController
```

**Comment by xuanzi23** [comment]
I try to convert to swift. Thanks

**Comment by bfeher** [comment]
I haven't tried it but it may be something along the lines of:
```swift
selectTabAtIndex(2, animated:true)
```

**Comment by pkgundam** [comment]
is it compatible with Swift3?

**Comment by xuanzi23** [comment]
@bfeher If I work with gesture, the underline highlight won't follow to the page.

**Comment by xuanzi23** [comment]
![screen shot 2016-12-30 at 10 06 09 am](https://cloud.githubusercontent.com/assets/19340910/21558602/abf576b4-ce77-11e6-8b18-2e855aaa9692.png)

**Comment by xuanzi23** [comment]
@bfeher sorry for the late reply
`func handleSwipes(_ sender:UISwipeGestureRecognizer) {
        
        if let swipeGesture = sender as? UISwipeGestureRecognizer {
            
            switch swipeGesture.direction {
            case UISwipeGestureRecognizerDirection.right:
                print("Swiped right")
                let selectedIndex: Int = self.tabBarController!.selectedIndex
                self.tabBarController!.selectedIndex = selectedIndex - 1
                
            case UISwipeGestureRecognizerDirection.left:
                print("Swiped left")
                let selectedIndex: Int = self.tabBarController!.selectedIndex
                self.tabBarController!.selectedIndex = selectedIndex + 1
                
            default:
                break
            }
        }
    }`

I create a gesture for handling the swipe gesture. So the user can change the content by using swipe but somehow the underline highlight not following with the active tab, so i wonder how to do that

**Comment by bfeher** [comment]
Hi @xuanzi23 

Have you tried to replace  
```swift
self.tabBarController!.selectedIndex = selectedIndex - 1
...
self.tabBarController!.selectedIndex = selectedIndex + 1
```

with  
```swift
self.tabBarController!.selectTabAtIndex(selectedIndex - 1, animated: true)
...
self.tabBarController!.selectTabAtIndex(selectedIndex + 1, animated: true)
```
?

**Comment by xuanzi23** [comment]
@bfeher 
It give me error "Value of type 'UITabBarController' has no member 'selectTabAtIndex'"

**Comment by bfeher** [comment]
Sorry you need to typecast self.tabBarController as a BFPaperTabBarController or instead of accessing self.tabBarController directly.

**Comment by xuanzi23** [comment]
@bfeher I access as 
`let abc = BFPaperTabBarController()` but still cannot.

**Comment by bfeher** [comment]
Sorry I was not being clear. Here is code that I have working for a UIViewController to allow it to swipe left and right between tabs:

```swift
import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let swipeRight = UISwipeGestureRecognizer(target: self, action: #selector(handleSwipes(_:)))
        swipeRight.direction = .right
        view .addGestureRecognizer(swipeRight)
        let swipeLeft = UISwipeGestureRecognizer(target: self, action: #selector(handleSwipes(_:)))
        swipeLeft.direction = .left
        view .addGestureRecognizer(swipeLeft)
    }

    func handleSwipes(_ sender:UISwipeGestureRecognizer) {
        
        if let swipeGesture = sender as? UISwipeGestureRecognizer {
            
            switch swipeGesture.direction {
            case UISwipeGestureRecognizerDirection.right:
                print("Swiped right")
                let selectedIndex: Int = self.tabBarController!.selectedIndex
                print("selected index = \(selectedIndex)")
                if let bfptbc = self.tabBarController! as? BFPaperTabBarController {
                    bfptbc.selectTab(at: max(selectedIndex - 1, 0), animated: true)
                    // max(selectedIndex - 1, 0) keeps our index in range
                }
                
            case UISwipeGestureRecognizerDirection.left:
                print("Swiped left")
                let selectedIndex: Int = self.tabBarController!.selectedIndex
                print("selected index = \(selectedIndex)")
                if let bfptbc = self.tabBarController! as? BFPaperTabBarController {
                    bfptbc.selectTab(at: min(selectedIndex + 1, (self.tabBarController?.viewControllers?.count)! - 1), animated: true)
                    // min(selectedIndex + 1, (self.tabBarController?.viewControllers?.count)! - 1) keeps our index in range
                }
                
            default:
                break
            }
        }
    }

}
```

**Comment by xuanzi23** [comment]
@bfeher Thanks a lot!

**Comment by bfeher** [comment]
Thank you for supporting this control :)
