### ISSUE TITLE
Bad title position on the iPhone X emulator

### ISSUE THREAD

**Issue by boyfox** [bfeher/BFPaperTabBarController#29]
Hi, thank you for great library!

I found following bug on the iPhone x emulator, look to screenshot:

![screen shot 2017-11-14 at 9 21 23 am](https://user-images.githubusercontent.com/3168694/32762825-96819ff0-c91d-11e7-808a-81e2c2eee734.png)

Do you have any suggestions how to fix it?

Thank you in advance!

**Comment by bfeher** [comment]
Hi @boyfox !

When I run the command `pod try BFPaperTabBarController` and get the default app up and running it works how iPhone X specifications state that it should:
![screen shot 2017-11-14 at 17 56 41](https://user-images.githubusercontent.com/3466708/32771212-6500dbce-c965-11e7-8f18-9ed12340b63c.png)


Are you doing anything custom with this control or maybe some AutoLayout issues with the new Safe Zones?

**Comment by boyfox** [comment]
HI @bfeher !, Sorry for later replying, i bought iphone x and checked again, same issuse:

![iphonex_bug](https://user-images.githubusercontent.com/3168694/33703301-5b9e195c-db49-11e7-95d1-5b57824fba24.png)

I'm using CustomUITabBar class for setting fixed height:
```
-(CGSize)sizeThatFits:(CGSize)size {
    CGSize sizeThatFits = [super sizeThatFits:size];
    sizeThatFits.height = 54; // 54pt - design in iphone 6 plus
    
    return sizeThatFits;
}
```
and i'm using vector images such as pdf files for icons.

others devices works fine:

![screen shot 2017-12-07 at 12 31 53 pm](https://user-images.githubusercontent.com/3168694/33703612-af319142-db4a-11e7-879c-ef3fcde56133.png)

Do you have any suggestion, i need increasing tab bar height just on Iphone X? can i get standart device tabbar height for checking?

**Comment by bfeher** [comment]
Hi @boyfox!

Hmm. This seems like an issue with the new [Safe Areas](https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area). Have you enabled them in your app? It looks like the content of the bar itself is pushed up correctly with safe zones, but the background isn't.

I can't reproduce this so I can only guess. Do you get the same results if you use a standard UITabBarController?

**Comment by boyfox** [comment]
Yes, @bfeher you are right, Safe area stayed turn off in my project. But i can't switch on it, because my deployment target is iOS 8.0 . 

Do you have any suggestions to fix it?

**Comment by bfeher** [comment]
When I updated my apps I had a problem where the entire UITabBar was below the Safe Area. I adjusted the Autolayout property and it worked perfectly. However what is strange in your case is that only the background and icons are in the original position while the bar itself is correctly positioned. Perhaps some of your auto layout constraints within the bar need new values when on the iPhone X? (Since you support iOS 8 and can't use Safe Area, maybe you can check if you are on the iPhone X and push up your constraints which are probably set to zero, to the height of the safe area?)

**Comment by boyfox** [comment]
ok @bfeher thank you for suggestions, you can close or remove this issue, because this is not a bug of library. Thank you for great library!

**Comment by bfeher** [comment]
@boyfox Sorry that I couldn't help more. If you find out that it is this library, or want me to look at some code, let me know :)

**Comment by boyfox** [comment]
Thank you @bfeher, you are best programmer! I removed custom UITabBar and works fine. Also works if I will increasing custom ui tabbar height if device model iphone X.

**Comment by bfeher** [comment]
;) You are too kind. I'm glad you could solve it!
