### ISSUE TITLE
Icons only tabbar items

### ISSUE THREAD

**Issue by malcommac** [bfeher/BFPaperTabBarController#9]
Is possible to use tabbaritems without label?

**Comment by bfeher** [comment]
Hi malcommac,

I haven't added any extra features on UITabBarItem. You should be able to achieve this in a few ways as detailed in these SO posts: 

http://stackoverflow.com/questions/12771212/custom-uitabbaritem-without-title-label

http://stackoverflow.com/questions/26494130/remove-tab-bar-item-text-show-only-image

http://stackoverflow.com/questions/16285205/moving-uitabbaritem-image-down
